export const novice5k = `novice5k,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const intermediate5k = `intermediate5k,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const advanced5k = `advanced5k,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const novice10k = `novice10k,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const intermediate10k = `intermediate10k,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const advanced10k = `advanced10k,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const noviceHM = `noviceHM,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const intermediateHM = `intermediateHM,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const advancedHM = `advancedHM,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const noviceMarathon = `noviceMarathon,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const intermediateMarathon = `intermediateMarathon,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;

export const advancedMarathon = `advancedMarathon,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 30 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 35 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 40 mins,REST;
Z,Z,Z,Z,Z,Z1: 20 mins,RACE DAY`;
